"""added_services_specialist_fields

Revision ID: 109248d82b7c
Revises: f9a1b2c3d4e5
Create Date: 2026-04-29 12:05:06.782202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '109248d82b7c'
down_revision: Union[str, None] = 'f9a1b2c3d4e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment_corporate_quota_usage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('corporate_code_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('appointments_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['corporate_code_id'], ['appointment_corporate_codes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointment_corporate_quota_usage_corporate_code_id'), 'appointment_corporate_quota_usage', ['corporate_code_id'], unique=False)
    op.create_index(op.f('ix_appointment_corporate_quota_usage_date'), 'appointment_corporate_quota_usage', ['date'], unique=False)
    op.drop_index('ix_telemed_payment_appointment_id', table_name='telemed_payment_records')
    op.drop_index('ix_telemed_payment_appointment_patient', table_name='telemed_payment_records')
    op.drop_index('ix_telemed_payment_created_at', table_name='telemed_payment_records')
    op.drop_index('ix_telemed_payment_invoice_no', table_name='telemed_payment_records')
    op.drop_index('ix_telemed_payment_patient_id', table_name='telemed_payment_records')
    op.drop_index('ix_telemed_payment_payment_token', table_name='telemed_payment_records')
    op.drop_index('ix_telemed_payment_status', table_name='telemed_payment_records')
    op.drop_index('ix_telemed_payment_status_created', table_name='telemed_payment_records')
    op.drop_index('ix_telemed_payment_transaction_id', table_name='telemed_payment_records')
    op.drop_table('telemed_payment_records')
    op.drop_table('appointment_requests')
    op.alter_column('services', 'consultation_fee',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_column('services', 'display_order')
    op.add_column('specialists', sa.Column('clinic_name', sa.String(), server_default='', nullable=False))
    op.add_column('specialists', sa.Column('clinic_photo_path', sa.String(), nullable=True))
    op.add_column('specialists', sa.Column('banner_image_path', sa.String(), nullable=True))
    op.add_column('specialists', sa.Column('consultation_fee', sa.Integer(), server_default='0', nullable=False))
    op.add_column('specialists', sa.Column('years_of_practice', sa.Integer(), nullable=True))
    op.add_column('specialists', sa.Column('hospital_affiliations', sa.String(), nullable=True))
    op.add_column('specialists', sa.Column('board_certifications', sa.String(), nullable=True))
    op.add_column('specialists', sa.Column('awards', sa.String(), nullable=True))
    op.add_column('specialists', sa.Column('insurance_tpa', sa.String(), nullable=True))
    op.add_column('specialists', sa.Column('insurance_shield_plan', sa.String(), nullable=True))
    op.drop_column('specialists', 'image_path')
    op.drop_column('specialists', 'insurance')
    op.drop_column('teleconsult_queues', 'hold_invoice_no')
    sa.Enum('PENDING', 'CONFIRMED', 'REJECTED', 'COMPLETED', name='requeststatus').drop(op.get_bind())
    op.sync_enum_values(
        enum_schema='public',
        enum_name='paymentstatus',
        new_values=['PAYMENT_CREATED', 'PAYMENT_AUTHORIZED', 'PAYMENT_CAPTURE_PENDING', 'PAYMENT_CAPTURED', 'PAYMENT_CANCELED', 'PAYMENT_EXPIRED', 'PAYMENT_FAILED', 'PAYMENT_SUCCESS'],
        affected_columns=[TableReference(table_schema='public', table_name='payment_logs', column_name='status'), TableReference(table_schema='public', table_name='payment_transactions', column_name='status')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='paymentstatus',
        new_values=['PAYMENT_CREATED', 'PAYMENT_CANCELED', 'PAYMENT_EXPIRED', 'PAYMENT_FAILED', 'PAYMENT_SUCCESS'],
        affected_columns=[TableReference(table_schema='public', table_name='payment_logs', column_name='status'), TableReference(table_schema='public', table_name='payment_transactions', column_name='status')],
        enum_values_to_rename=[],
    )
    sa.Enum('PENDING', 'CONFIRMED', 'REJECTED', 'COMPLETED', name='requeststatus').create(op.get_bind())
    op.add_column('teleconsult_queues', sa.Column('hold_invoice_no', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('specialists', sa.Column('insurance', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('specialists', sa.Column('image_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('specialists', 'insurance_shield_plan')
    op.drop_column('specialists', 'insurance_tpa')
    op.drop_column('specialists', 'awards')
    op.drop_column('specialists', 'board_certifications')
    op.drop_column('specialists', 'hospital_affiliations')
    op.drop_column('specialists', 'years_of_practice')
    op.drop_column('specialists', 'consultation_fee')
    op.drop_column('specialists', 'banner_image_path')
    op.drop_column('specialists', 'clinic_photo_path')
    op.drop_column('specialists', 'clinic_name')
    op.add_column('services', sa.Column('display_order', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('services', 'consultation_fee',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.create_table('appointment_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('specialisation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('specialist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('patient_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('patient_dob', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('contact_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('preferred_days', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('preferred_time', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reason', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'CONFIRMED', 'REJECTED', 'COMPLETED', name='requeststatus', create_type=False), autoincrement=False, nullable=False),
    sa.Column('status_message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('submitted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['specialisation_id'], ['specialisations.id'], name='appointment_requests_specialisation_id_fkey'),
    sa.ForeignKeyConstraint(['specialist_id'], ['specialists.id'], name='appointment_requests_specialist_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='appointment_requests_pkey')
    )
    op.create_table('telemed_payment_records',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('appointment_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('payment_token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('invoice_no', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('authorized_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('consultation_fee', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=True),
    sa.Column('medication_fee', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False),
    sa.Column('delivery_fee', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False),
    sa.Column('captured_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(), server_default=sa.text("'THB'::character varying"), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), server_default=sa.text("'pending_auth'::character varying"), autoincrement=False, nullable=False),
    sa.Column('is_test_transaction', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('authorized_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('captured_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('voided_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('void_reason', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='telemed_payment_records_pkey'),
    sa.UniqueConstraint('appointment_id', name='uq_telemed_payment_appointment_id'),
    sa.UniqueConstraint('invoice_no', name='uq_telemed_payment_invoice_no'),
    sa.UniqueConstraint('transaction_id', name='uq_telemed_payment_transaction_id')
    )
    op.create_index('ix_telemed_payment_transaction_id', 'telemed_payment_records', ['transaction_id'], unique=False)
    op.create_index('ix_telemed_payment_status_created', 'telemed_payment_records', ['status', 'created_at'], unique=False)
    op.create_index('ix_telemed_payment_status', 'telemed_payment_records', ['status'], unique=False)
    op.create_index('ix_telemed_payment_payment_token', 'telemed_payment_records', ['payment_token'], unique=False)
    op.create_index('ix_telemed_payment_patient_id', 'telemed_payment_records', ['patient_id'], unique=False)
    op.create_index('ix_telemed_payment_invoice_no', 'telemed_payment_records', ['invoice_no'], unique=False)
    op.create_index('ix_telemed_payment_created_at', 'telemed_payment_records', ['created_at'], unique=False)
    op.create_index('ix_telemed_payment_appointment_patient', 'telemed_payment_records', ['appointment_id', 'patient_id'], unique=False)
    op.create_index('ix_telemed_payment_appointment_id', 'telemed_payment_records', ['appointment_id'], unique=False)
    op.drop_index(op.f('ix_appointment_corporate_quota_usage_date'), table_name='appointment_corporate_quota_usage')
    op.drop_index(op.f('ix_appointment_corporate_quota_usage_corporate_code_id'), table_name='appointment_corporate_quota_usage')
    op.drop_table('appointment_corporate_quota_usage')
    # ### end Alembic commands ###
