"""restore_appointment_requests

Revision ID: 594be2feb6ea
Revises: 109248d82b7c
Create Date: 2026-04-29 13:00:34.147009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '594be2feb6ea'
down_revision: Union[str, None] = '109248d82b7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('PENDING', 'CONFIRMED', 'REJECTED', 'COMPLETED', name='requeststatus').create(op.get_bind())
    op.create_table('appointment_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('specialisation_id', sa.Integer(), nullable=False),
    sa.Column('specialist_id', sa.Integer(), nullable=False),
    sa.Column('patient_name', sa.String(), nullable=False),
    sa.Column('patient_dob', sa.String(), nullable=True),
    sa.Column('contact_number', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('preferred_days', sa.String(), nullable=True),
    sa.Column('preferred_time', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'CONFIRMED', 'REJECTED', 'COMPLETED', name='requeststatus', create_type=False), nullable=False),
    sa.Column('status_message', sa.String(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['specialisation_id'], ['specialisations.id'], ),
    sa.ForeignKeyConstraint(['specialist_id'], ['specialists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointment_requests')
    sa.Enum('PENDING', 'CONFIRMED', 'REJECTED', 'COMPLETED', name='requeststatus').drop(op.get_bind())
    # ### end Alembic commands ###
