"""added service_id and made specialist_id optional

Revision ID: 59fe9ecf4385
Revises: 690381b90bea
Create Date: 2026-04-29 15:06:05.805838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59fe9ecf4385'
down_revision: Union[str, None] = '690381b90bea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment_requests', sa.Column('service_id', sa.Integer(), nullable=True))
    op.alter_column('appointment_requests', 'specialist_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'appointment_requests', 'services', ['service_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointment_requests', type_='foreignkey')
    op.alter_column('appointment_requests', 'specialist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('appointment_requests', 'service_id')
    # ### end Alembic commands ###
