"""renamed pending status to requested

Revision ID: 690381b90bea
Revises: da35b3ac3600
Create Date: 2026-04-29 14:26:13.271609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '690381b90bea'
down_revision: Union[str, None] = 'da35b3ac3600'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='requeststatus',
        new_values=['REQUESTED', 'CONFIRMED', 'REJECTED', 'COMPLETED', 'RESCHEDULED', 'CANCELLED'],
        affected_columns=[TableReference(table_schema='public', table_name='appointment_requests', column_name='status')],
        enum_values_to_rename=[('PENDING', 'REQUESTED')],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='requeststatus',
        new_values=['PENDING', 'CONFIRMED', 'REJECTED', 'COMPLETED', 'RESCHEDULED', 'CANCELLED'],
        affected_columns=[TableReference(table_schema='public', table_name='appointment_requests', column_name='status')],
        enum_values_to_rename=[('REQUESTED', 'PENDING')],
    )
    # ### end Alembic commands ###
