"""add_reschedule_cancel_statuses

Revision ID: 82f2684e8f22
Revises: 594be2feb6ea
Create Date: 2026-04-29 14:07:57.026396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '82f2684e8f22'
down_revision: Union[str, None] = '594be2feb6ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='requeststatus',
        new_values=['PENDING', 'CONFIRMED', 'REJECTED', 'COMPLETED', 'RESCHEDULED', 'CANCELLED'],
        affected_columns=[TableReference(table_schema='public', table_name='appointment_requests', column_name='status')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='requeststatus',
        new_values=['PENDING', 'CONFIRMED', 'REJECTED', 'COMPLETED'],
        affected_columns=[TableReference(table_schema='public', table_name='appointment_requests', column_name='status')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
