"""add_cascade_delete_to_specialisation

Revision ID: a0c0453f17a3
Revises: 62aa7e4fa49f
Create Date: 2026-05-01 12:41:55.548294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0c0453f17a3'
down_revision: Union[str, None] = '62aa7e4fa49f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('appointment_requests_specialisation_id_fkey', 'appointment_requests', type_='foreignkey')
    op.create_foreign_key(None, 'appointment_requests', 'specialisations', ['specialisation_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('services_specialisation_id_fkey', 'services', type_='foreignkey')
    op.create_foreign_key(None, 'services', 'specialisations', ['specialisation_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('specialists_specialisation_id_fkey', 'specialists', type_='foreignkey')
    op.create_foreign_key(None, 'specialists', 'specialisations', ['specialisation_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'specialists', type_='foreignkey')
    op.create_foreign_key('specialists_specialisation_id_fkey', 'specialists', 'specialisations', ['specialisation_id'], ['id'])
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.create_foreign_key('services_specialisation_id_fkey', 'services', 'specialisations', ['specialisation_id'], ['id'])
    op.drop_constraint(None, 'appointment_requests', type_='foreignkey')
    op.create_foreign_key('appointment_requests_specialisation_id_fkey', 'appointment_requests', 'specialisations', ['specialisation_id'], ['id'])
    # ### end Alembic commands ###
