"""added display_order to services

Revision ID: da35b3ac3600
Revises: 82f2684e8f22
Create Date: 2026-04-29 14:13:25.927121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da35b3ac3600'
down_revision: Union[str, None] = '82f2684e8f22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('display_order', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'display_order')
    # ### end Alembic commands ###
